-- Account master (copybook CVACT01Y). LOAD_SEQ keeps the legacy file order
-- so the rewritten master (BR-16) comes out in input order.
CREATE TABLE ACCOUNT (
    ACCT_ID BIGINT PRIMARY KEY,
    LOAD_SEQ INTEGER NOT NULL,
    ACTIVE_STATUS VARCHAR(1) NOT NULL,
    CURR_BAL DECIMAL(12,2) NOT NULL,
    CREDIT_LIMIT DECIMAL(12,2) NOT NULL,
    CASH_CREDIT_LIMIT DECIMAL(12,2) NOT NULL,
    OPEN_DATE VARCHAR(10) NOT NULL,
    EXPIRATION_DATE VARCHAR(10) NOT NULL,
    REISSUE_DATE VARCHAR(10) NOT NULL,
    CURR_CYC_CREDIT DECIMAL(12,2) NOT NULL,
    CURR_CYC_DEBIT DECIMAL(12,2) NOT NULL,
    ADDR_ZIP VARCHAR(10) NOT NULL,
    GROUP_ID VARCHAR(10) NOT NULL
);
