CREATE TABLE CTL_XFER_PARM (
    BOOK_ID CHAR(10) NOT NULL,
    FEE_PCT DECIMAL(7,6) NOT NULL,
    FEE_CAP DECIMAL(11,2) NOT NULL,
    EFF_DT DATE NOT NULL,
    EXP_DT DATE NOT NULL,
    PRIMARY KEY (BOOK_ID, EFF_DT)
);
