CREATE TABLE XFER_FEE_LEDGER (
    TRAN_ID CHAR(16) PRIMARY KEY,
    TRAN_DT DATE NOT NULL,
    SRC_ACCT_ID DECIMAL(11,0) NOT NULL,
    TGT_ACCT_ID DECIMAL(11,0) NOT NULL,
    BOOK_ID CHAR(10) NOT NULL,
    TRAN_AMT DECIMAL(11,2) NOT NULL,
    FEE_AMT DECIMAL(11,2) NOT NULL,
    CAP_APPLIED CHAR(1) NOT NULL,
    POSTED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
